import type { Metadata } from "next";
import AppHeader from "@/components/AppHeader/AppHeader";
import QueryProvider from "./query-provider";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Shop app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        <QueryProvider>
          <main>{children}</main>
        </QueryProvider>
      </body>
    </html>
  );
}
